# Generated by Django 3.2 on 2021-05-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('fome_id', models.AutoField(primary_key=True, serialize=False)),
                ('room', models.CharField(max_length=128)),
                ('user_id', models.CharField(max_length=128)),
                ('service', models.CharField(max_length=128)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('equip', models.CharField(max_length=128)),
                ('state', models.CharField(choices=[('已完成', '已完成'), ('待完成', '待完成')], default='待完成', max_length=128)),
            ],
            options={
                'db_table': 'Equipment',
            },
        ),
    ]
