# Generated by Django 3.2 on 2021-05-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('m', '男'), ('f', '女')], default='m', max_length=10, verbose_name='性别')),
                ('department', models.CharField(default='技术部', max_length=30, verbose_name='部门')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('image', models.FileField(blank=True, null=True, upload_to='goods', verbose_name='图片')),
                ('identity', models.CharField(choices=[('user', '用户'), ('admin', '管理员'), ('staff', '后勤')], default='user', max_length=10, verbose_name='身份')),
                ('level', models.IntegerField(default=0)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'User',
                'ordering': ['c_time'],
            },
        ),
    ]
