# Generated by Django 3.2 on 2021-05-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_id', models.CharField(max_length=128, unique=True, verbose_name='编号')),
                ('conference_capacity', models.IntegerField(verbose_name='容量')),
                ('conference_authorization', models.IntegerField(verbose_name='权限')),
                ('conference_status', models.IntegerField(verbose_name='状态')),
                ('conference_createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('conference_updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'conference',
            },
        ),
    ]
